#!/bin/bash

# c3c compile-run $(fd . src/ --type f) --output-dir build/
# compile && get status && set status color
c3c compile $(fd . src/ --type f) --output-dir build/ && status="\x1b[92m" || status="\x1b[91m"

# print status color
echo -en "$status"

# print divider
printf %"$(($COLUMNS - 1))"s | tr " " "="

# reset color
echo -e "\x1b[m"

# run executable
./$(fd . build/ --type f)
